#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : intelhex
Version  : 2.3.0
Release  : 20
URL      : https://github.com/bialix/intelhex/archive/2.3.0/intelhex-2.3.0.tar.gz
Source0  : https://github.com/bialix/intelhex/archive/2.3.0/intelhex-2.3.0.tar.gz
Summary  : Python library for Intel HEX files manipulations
Group    : Development/Tools
License  : BSD-3-Clause
Requires: intelhex-bin = %{version}-%{release}
Requires: intelhex-license = %{version}-%{release}
Requires: intelhex-python = %{version}-%{release}
Requires: intelhex-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(py)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
Python IntelHex library
***********************
Introduction
------------
The Intel HEX file format is widely used in microprocessors and microcontrollers
area (embedded systems etc) as the de facto standard
for representation of code to be programmed into microelectronic devices.

%package bin
Summary: bin components for the intelhex package.
Group: Binaries
Requires: intelhex-license = %{version}-%{release}

%description bin
bin components for the intelhex package.


%package license
Summary: license components for the intelhex package.
Group: Default

%description license
license components for the intelhex package.


%package python
Summary: python components for the intelhex package.
Group: Default
Requires: intelhex-python3 = %{version}-%{release}

%description python
python components for the intelhex package.


%package python3
Summary: python3 components for the intelhex package.
Group: Default
Requires: python3-core
Provides: pypi(intelhex)

%description python3
python3 components for the intelhex package.


%prep
%setup -q -n intelhex-2.3.0
cd %{_builddir}/intelhex-2.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1644188056
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/intelhex
cp %{_builddir}/intelhex-2.3.0/LICENSE.txt %{buildroot}/usr/share/package-licenses/intelhex/afe5cf57dace507920199f9f31f266dd66cd9765
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bin2hex.py
/usr/bin/hex2bin.py
/usr/bin/hex2dump.py
/usr/bin/hexdiff.py
/usr/bin/hexinfo.py
/usr/bin/hexmerge.py

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/intelhex/afe5cf57dace507920199f9f31f266dd66cd9765

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
